### ISSUE TITLE
What file has the code for displaying Insulin Delivery/Pump Event Data?

### ISSUE THREAD

**Issue by Praxiteles** [LoopKit/LoopKit#108]
We are looking to clean up the display of the text on the Insulin Delivery/Pump Event Data to make it a bit more useful. Which file handles that code? Attached is a picture of that screen. 
![img_2490](https://cloud.githubusercontent.com/assets/1495948/24328850/f3d75f68-11a9-11e7-93f4-c7f9715217c7.PNG)

**Comment by ps2** [comment]
The code building up the string is here: https://github.com/LoopKit/LoopKit/blob/master/InsulinKit/UI/InsulinDeliveryTableViewController.swift#L379-L395

The bulk of the description comes from the debugDescription method on the individual entries themselves, which can be overridden.

**Comment by ps2** [comment]
Gitter is a good place to ask development questions. Github issues are best left for things we want to track over time.
