### ISSUE TITLE
Swift version blocks build

### ISSUE THREAD

**Issue by jwalsh77** [LoopKit/LoopKit#174]
Build is blocked as:Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /Users/mac/Downloads/Loop-master/Carthage/Build/iOS/SwiftCharts.framework/Modules/SwiftCharts.swiftmodule/arm64.swiftmodule
Have tried online suggestions to correct this to no avail. Does anyone have a suggestion?
Thanks,
John

**Comment by vpdn** [comment]
Swift is not ABI stable yet and it sounds like your framework is compiled with a different swift version than your project. Have you tried to clean and rebuild the carthage built frameworks yet?

Clean the derived data:
```
rm -rf ~/Library/Caches/org.carthage.CarthageKit/DerivedData
```

Remove the builds in the carthage folder of your project
```
rm -rf <yourProjectFolder>/Carthage/Build
```

Clean the derived folders from Xcode
```
rm -rf /Users/<YourUserID>/Library/Developer/Xcode/DerivedData
```

Clean Xcode build artefacts with alt+shift+cmd+k

Then update (or bootstrap) Carthage

```
carthage bootstrap --platform iOS
```

**Comment by rgitty** [comment]
I am getting the same/similar error shown below running the commands above didn't resolve.  I also uninstalled brew, reinstalled brew and Carthage with the same error resulting in Xcode build.  I would downgrade to Xcode 9.0 but I can't location older version on Apple developer portal.



>Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /Users/<username>/Downloads/Loop-master-2 DL 2017-11-15 584/Carthage/Build/iOS/SwiftCharts.framework/Modules/SwiftCharts.swiftmodule/x86_64.swiftmodule

**Comment by jwalsh77** [comment]
Like rgitty, the code did not fix the issue for me. Could not get "carthage bootstrap" to perform but still no joy after reinstalling everything. Is Swift 4.02 so different from 4.0 that it should block the build?

**Comment by GBRacerX1** [comment]
Is this the same reason we can't upload to test flight for our own use.

**Comment by ps2** [comment]
Testflight uploads should be working.
