### ISSUE TITLE
Loop won't run because of missing glucose data but Dexcom shows updated data

### ISSUE THREAD

**Issue by AztecWarriorHello** [LoopKit/LoopKit#178]
Hi.  This is the first time I am submitting an issue so please let me know if I am using this forum incorrectly.  First, a big THANK YOU to everyone who has made Loop possible - it has significantly improved my daughter's life and the well being of our entire family!

Now to the issue.  We have frequently been getting a red loop on my daughter's iPhone.  When clicked, it gives a missing blood glucose error.  The blood sugar shown in Loop is also stale with a yellow exclamation mark.  When the blood sugar is clicked on, the Dexcom app opens up BUT shows a current blood sugar is shown.  This error may persist for quite a while.  The last time this happened I noticed that the pump data was also stale.  In the Loop app I went into settings, Riley Link, and clicked on Read Pump Status to confirm that there was a connection (there was).  A few minutes after doing this, Loop began running again.  Is the stale blood glucose error related to the stale pump data?  Am I somehow "forcing" a blood sugar and pump data update by fetching the Pump Status?  Is there a way to prevent this from happening in the future?  We am running LoopV.1.4.0 - would updating to the latest version help?  Thank you very much for your thoughts.

**Comment by dm61** [comment]
Hi @AztecWarriorHello! The symptoms you are describing seem to point to the possibility that your Loop app may occasionally be crashing in the background. 

This place is for issues related to LoopKit, which is a set of frameworks the Loop app is based on. It is likely that more people will notice and respond to your questions if you open it as an issue for the Loop app itself, here: https://github.com/LoopKit/Loop/issues. For example, there is already an open issue that might be related to what you are seeing: https://github.com/LoopKit/Loop/issues/601.

**Comment by AztecWarriorHello** [comment]
@dm61, thank you so much!  I will certainly post my query in the correct place and I really appreciate you pointing me to the related open issue.  All the best!
