### ISSUE TITLE
Facial Recognition Not Working on iPhone X after latest builds

### ISSUE THREAD

**Issue by JKeller86** [LoopKit/LoopKit#205]
It appears multiple users are having issues with this... I personally still have the original build (~2 months ago) on my phone, which is not affected. 

New users and users who are rebuilding the app as of recently (could be the Xcode update?) are having to enter a passcode instead of utilizing the facial recognition or touch ID.

**Comment by JKeller86** [comment]
I just experienced this myself. 

Steps to reproduce: 
1. Delete Loop from your iPhone X 
2. Rebuild Loop
3. Facial Recognition **should** not work 

I had rebuilt a few times before, but never deleted the original Loop app, and this was not an issue. It wasn't until fully deleting the app, then rebuilding that I ran into this issue personally.

**Comment by JKeller86** [comment]
Tested a theory of completely wiping the device and reinstalling, I was never prompted to allow Face ID even after a clean install of the OS and a clean install of Loop.

**Comment by Kdisimone** [comment]
https://github.com/LoopKit/Loop/pull/710
