### ISSUE TITLE
"Bolus may not have succeeded", but it always does.

### ISSUE THREAD

**Issue by aarondfrancis** [LoopKit/LoopKit#239]
I just switched to my backup loopable pump, the Medtronic 715 with firmware 2.3A 1.1. 

Every time I bolus, Loop tells me it may not have succeeded and that the pump responded unexpectedly. Yet every time it does actually work. Is this a known issue? Is there a workaround or a set of logs I can give you to help?

Thanks!

**Comment by aarondfrancis** [comment]
Hey there, is there any more information I can provide that would help diagnose this issue?

**Comment by Kdisimone** [comment]
https://loopkit.github.io/loopdocs/operation/features/bolus/#bolus-failure-notifications

**Comment by aarondfrancis** [comment]
Thanks for point me to that article. 

For those following, you eventually end up here: https://github.com/LoopKit/Loop/issues/587
