### ISSUE TITLE
Minor issue - version display

### ISSUE THREAD

**Issue by bdr1177** [LoopKit/LoopKit#298]
The loop dev version is not displaying correctly in the settings.  I downloaded and installed the dev branch yesterday, but in settings it is displaying as “LOOP V.1.10.0.”   I’m sure this is the dev branch because it has the options to test Omnipod beeps and enable the beeps. 

![IMG_0002](https://user-images.githubusercontent.com/8519000/64540689-91b33100-d2ee-11e9-92ea-6c37ffcf34d0.jpg)

![IMG_0003](https://user-images.githubusercontent.com/8519000/64540706-97a91200-d2ee-11e9-8bdc-b597208ddcd0.jpg)

**Comment by Kdisimone** [comment]
Yes. That is current dev version. The dev version number does not increment with every additional feature/change in dev. When a master release is done , that’s usually when dev version number increments as well

Closing issue since this is normal behavior. 👍

**Comment by Kdisimone** [comment]
Actually, I don’t appear to have option to close comment here (@ps2)

**Comment by bdr1177** [comment]
@Kdisimone  I certainly defer to your judgment and expertise.  But just to clarify, I wasn't referring to the number not incrementing, I was referring to the fact that the version doesn't indicate "DEV."  Maybe that's not an issue.  But I thought I saw a post earlier where Kate Farnsworth was helping someone and asking for the version info from the setting screen to confirm that it was the DEV version.  I got the impression (maybe incorrectly) that DEV should be part of the version name that displays in settings.  Sorry if I'm mistaken.

**Comment by Kdisimone** [comment]
Ah, my bad. I see what you’re saying now. 

Maybe revise this note then and file under LoopKit/Loop instead of LoopKit/LoopKit. It’s not a huge deal and probably just an oversight. Pete has had an awful lot of version tracking going between Tidepool, Loop, loopworkspace and many Pr branches. Just a bump that will get fixed eventually.

**Comment by bdr1177** [comment]
@Kdisimone  Will do.  I understand its a really minor issue.  I just saw a potential for miscommunication between folks asking for help and people giving help in the looped group and was trying to do my little part to help out.  I'll close this comment and repost in LoopKit/Loop as you suggested.

**Comment by ps2** [comment]
Yes, I removed the dev suffix as it causes issues with people doing TestFlight builds. I would like to find a way to include more details about the build source into the the display and issue report, but haven't dug into that. Was thinking a script that would capture the path of the build, and any git information (rev, branch, repo) if present.
