### ISSUE TITLE
New User - Loop 2.0 - iPhone 11 - cannot locate Riley Link via BT

### ISSUE THREAD

**Issue by scooper55** [LoopKit/LoopKit#320]
I just downloaded and installed v2.0 - got a new rileylink, new Iphone 11 and cannot connect the Rileylink to the iPhone via loop.  It won't show in the list.

**Comment by Kdisimone** [comment]
Go to iPhone settings, privacy, bluetooth. Turn on Loop's slider in the list of apps allowed to use bt

**Comment by scooper55** [comment]
> Go to iPhone settings, privacy, bluetooth. Turn on Loop's slider in the list of apps allowed to use bt

T H A N K  Y O U !!!   That was it!!
