### ISSUE TITLE
Extend range for "Suspend Insulin Delivery" 

### ISSUE THREAD

**Issue by metahgva** [LoopKit/LoopKit#500]
Hello,
for Omnipod Dash, when setting the "Suspend Insulin Delivery" we can only select between 30 minutes, 1 hour, 1 hour 30 minutes, and 2 hours. With my diabetes, I need to be able to turn off the pump for much longer sometimes for 6 hours or indefinitely. 

Where could I change these settings?

**Comment by marionbarker** [comment]
The suspend command turns off basal delivery until you manually turn it back on again. Those are times for the first reminder that insulin delivery has been suspended. 

The manual temp basal command automatically resumes delivery of scheduled basal after the duration expires. It can be selected in half hour intervals and is limited to 12 hours as the maximum duration. That limit is determined by the pod firmware. 

Please close this issue and use zulipchat or Facebook for questions.

**Comment by metahgva** [comment]
Thanks for the clarification, @marionbarker, you're correct.

**Comment by metahgva** [comment]
Closed
