### ISSUE TITLE
Carthage is used to manage framework dependencies. It will need to be installed on your Mac to build and run the app, but most users won't have a need to explicitly rebuild any dependencies.

### ISSUE THREAD

**Issue by liushengxu** [LoopKit/LoopKit#86]
Dear  ： 
how to solution this question ？？？

Loop-master/Loop/Managers/DiagnosticLogger+LoopKit.swift:11:8: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: /Users/xuliusheng/Downloads/Loop-master/Carthage/Build/iOS/LoopKit.framework/Modules/LoopKit.swiftmodule/x86_64.swiftmodule

**Comment by Kdisimone** [comment]
Update your Xcode to 8.1
